"""
Django settings for quickstartproject project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 22-10-2025 - loading variables for Django Secret Key + MySQL info
from dotenv import load_dotenv
load_dotenv()

# 20-05-2026 - For working with databases at Render and Neon Cloud
import dj_database_url

# 20-05-2026 - For working with databases at Render and Neon Cloud
DATABASE_URL=os.getenv('DATABASE_URL')

# Getting the secret key from env locally and from enviroment variable in production
SECRET_KEY=os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# With DEBUG=False 404 errors will be directed to a default 404 template
# Not: Django will display a 404.html if you have created one :-)
DEBUG = False

# 20-05-2026 - Needed for locally developing but dont work at Azure !
# DEVELOPEMENT - Disable for Production !
# ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# 20-05-2026 - Needed for Azure but dont work when running locally developing !
# PRODUCTION - Disable for Developement !
ALLOWED_HOSTS = ['pso-django-demo.azurewebsites.net']

# 20-05-2026 - Needed at Azure to avoid 403 forbidden when trying to login to the Django Admin Backend
# PRODUCTION
CSRF_TRUSTED_ORIGINS = ['https://pso-django-demo.azurewebsites.net']

# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hello_azure',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Add whitenoise middleware after the security middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'quickstartproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quickstartproject.wsgi.application'

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''

# 20-05-2026 - PostgreSQL with a Serverless setup at Neon Cloud
DATABASES = {

    'default': dj_database_url.config(

        default=DATABASE_URL,

        conn_max_age=600,
        ssl_require=True, 
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# 20-05-2026 - Needed at Azure but dont work when running locally developing !
# PRODUCTION
STATICFILES_DIRS = (str(BASE_DIR.joinpath('static')),)

STATIC_URL = 'static/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 20-05-2026 - Works at Azure but dont work when running locally developing !
# PRODUCTION
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 20-05-2026 - Needed for locally developing and seems to work at Azure too !
# DEVELOPEMENT
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
